framework:
    secret: '%env(APP_SECRET)%'
    translator:
        fallbacks: [ "fr" ]
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
    php_errors:
        log: true
    serializer:
        enabled: true