security:
    always_authenticate_before_granting: true

    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: lazy
            guard:
                authenticators:
                    - App\Security\AppAuthenticator
            user_checker: App\Security\UserChecker
            logout:
                path: logout
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 2592000

    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/candidate/dashboard, roles: ROLE_CANDIDATE }
         - { path: ^/recruiter/dashboard, roles: ROLE_RECRUITER }
         - { path: ^/offer/create, roles: ROLE_RECRUITER }
         - { path: ^/profile, roles: [ROLE_CANDIDATE, ROLE_RECRUITER] }
