parameters:
    api_siren_token: '%env(API_SIREN_TOKEN)%'
    api_siren_url_siret: '%env(API_SIREN_URL_SIRET)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
