parameters:
    api_siren_token: '%env(API_SIREN_TOKEN)%'
    api_siren_url_siret: '%env(API_SIREN_URL_SIRET)%'
    api_google_map_key: '%env(API_GOOGLE_MAP_KEY)%'
    app.path.product_images: /public/user_avatars/

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
